### ISSUE TITLE
Typed JSON property binding does not work with LINQ queries

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#38]
I have a JSON view-model and an array property inside, the property is bound to a database query using LINQ.

```cs
public IEnumerable<Database.Item> Items
{
    get
    {
        return DbLinq.Objects<Database.Item>().OrderBy(x => x.Index);
    }
}
```

This construction throws the following exception when trying to open the page:

```
"System.InvalidCastException: Unable to cast object of type 'Database.Item' to type 'System.Collections.IEnumerable'.
   at Starcounter.Linq.QueryExecutor`1.Execute[TResult](String sql, Object[] variables, QueryResultMethod queryResultMethod) in G:\GitHub\Starcounter\Starcounter.Linq\src\Starcounter.Linq\QueryExecutor.cs:line 29
   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression) in G:\GitHub\Starcounter\Starcounter.Linq\src\Starcounter.Linq\QueryContext.cs:line 26
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression) in G:\GitHub\Starcounter\Starcounter.Linq\src\Starcounter.Linq\QueryProvider.cs:line 22
   at Starcounter.Linq.Queryable`1.System.Collections.IEnumerable.GetEnumerator() in G:\GitHub\Starcounter\Starcounter.Linq\src\Starcounter.Linq\Queryable.cs:line 35
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 539
   at Starcounter.Templates.TArray`1.GetAndCacheValue(Json parent) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 129
   at Starcounter.XSON.NewtonSoftSerializer.GetValue(TObjArr template, Json parent, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 598
   at Starcounter.XSON.NewtonSoftSerializer.ScopeAndSerializeArray(Json json, Template template, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 291
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 241
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.NewtonSoftSerializer.<>c__DisplayClass10_1.<Serialize>b__0() in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 79
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, TextWriter textWriter, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 82
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 61
   at Starcounter.Internal.PuppetRestHandler.CreateJsonBodyResponse(Session session, Json root) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 229
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-12012\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2147467262
"
```

If property returns an array, then everything works.

```cs
public IEnumerable<Database.Item> Items
{
    get
    {
        return DbLinq.Objects<Database.Item>().OrderBy(x => x.Index).ToArray();
    }
}
```

Source code for this example is available here - [miyconst/Playground/tree/linq](https://github.com/miyconst/Playground/tree/linq).

```
Starcounter.Linq 0.5.0
```

```
Starcounter-RC-2.3.1.8061 (Dec 12, 2017 1:02:27 AM)
```

@un-tone feel free to ask @chrhol for any assistance with Typed JSON.

**Comment by un-tone** [comment]
Closing as done

**Comment by miyconst** [comment]
@un-tone please notify me when the fix will be released as a NuGet package, so I can test it again.
