### ISSUE TITLE
String.Contains with a variable generates wrong number of parameters

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#43]
I have the following piece of LINQ to SQL:

```cs
string key = "some value";
this.Products.Data = DbLinq.Objects<Product>().Where(x => x.Barcode.Contains(key));
```

It fails with the following exception:

```
System.ArgumentException: Incorrect number of SQL parameters, which should be: 1
	   at Starcounter.Query.Execution.ExecutionEnumerator.SetVariables(Object[] sqlParams)
	   at Starcounter.QueryResultRowsImpl`1.GetExecutionEnumerator()
	   at Starcounter.QueryResultRowsImpl`1.GetEnumerator()
	   at Starcounter.QueryResultRows`1.GetEnumerator() in C:\TeamCity\BuildAgent\work\sc-15221\Level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 14
	   at Starcounter.Linq.Queryable`1.GetEnumerator()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

```

Let me know if you need me to debug it further.

**Noe:** the same code works with a literal:

```cs
this.Products.Data = DbLinq.Objects<Product>().Where(x => x.Barcode.Contains("some value"));
```

**Comment by un-tone** [comment]
@miyconst the bug is fixed. The new packages 1.0.1 and 2.0.1 are released and published.
