### ISSUE TITLE
Exception when querying a generic

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter.Linq#45]
Following code results in a exception:
```cs
    public class Program
    {
        static void Main()
        {
            Run<Session>();
        }

        private static void Run<T>() where T:ISession
        {
            DbLinq.Objects<T>()
                .FirstOrDefault(session => session.SessionId == 1);
        }
    }

    public interface ISession
    {
        int SessionId { get; set; }
    }

    public class Session : ISession
    {
        public int SessionId { get; set; }
    }
```

The exception:
```
System.NotSupportedException: Specified method is not supported.
   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMember(MemberExpression node, QueryBuilder`1 state, Boolean specifyValueForBoolean)
   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMember(MemberExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinaryEquality(Expression left, Expression right, QueryBuilder`1 state, Boolean isEqualsSign)
   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinaryEquality(BinaryExpression node, QueryBuilder`1 state, Boolean isEqualsSign)
   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinary(BinaryExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.RootVisitor`1.VisitLambda(LambdaExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
   at Starcounter.Linq.Queryable`1.FirstOrDefault(Expression`1 predicate)
   at StarcounterApplication3.Program.Run[T]() in C:\Users\joozek\dev\authorization\StarcounterApplication3\Program.cs:line 17
   at StarcounterApplication3.Program.Main() in C:\Users\joozek\dev\authorization\StarcounterApplication3\Program.cs:line 12
```

The reason seems to be that the selector expression contains a cast to `ISession`, which is not supported.

**Comment by un-tone** [comment]
Fixed in versions [1.1](https://github.com/Starcounter/Starcounter.Linq/releases/tag/1.1.0), [2.1](https://github.com/Starcounter/Starcounter.Linq/releases/tag/2.1.0), [3.1](https://github.com/Starcounter/Starcounter.Linq/releases/tag/3.1.0)
