### ISSUE TITLE
Implement GetObjectNo method support

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#47]
Currently it's not possible to sort or filter by the object number using LINQ. The following statement fails:

```cs
IEnumerable<Item> query = DbLinq.Objects<Item>().OrderBy(x => x.GetObjectNo());
```

```
System.NotSupportedException: Specified method is not supported.
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.VisitMethodCall(MethodCallExpression node, T state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.VisitLambda(LambdaExpression node, T state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.VisitUnary(UnaryExpression node, T state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.RootVisitor`1.VisitOrderBy(MethodCallExpression node, QueryBuilder`1 state, Boolean asc)
   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
   at Starcounter.Linq.Queryable`1.GetEnumerator()
   at Playground.Program.<>c__DisplayClass0_0.<Main>b__4() in C:\Users\Const\Documents\GitHub\Playground\Playground\Program.cs:line 85
   at Starcounter.Db.TransactAsyncInternal(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-18006\Level1\src\Starcounter\Db.cs:line 295
   at Starcounter.Db.Transact(Action action, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-18006\Level1\src\Starcounter\Db.cs:line 515
   at Playground.Program.<>c.<Main>b__0_0() in C:\Users\Const\Documents\GitHub\Playground\Playground\Program.cs:line 78
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-18006\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 202
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-18006\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 95
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-18006\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 359
HResult=-2146233067

More information about this error may be available in the server error log.
```

**Comment by un-tone** [comment]
Resolved.
