### ISSUE TITLE
Counting ordered objects throws SqlException

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Starcounter.Linq#48]
I have some `IQueryable<T> data` which I first order by using method like `data.OrderBy(x => x.FirstName)` and then I'm trying to call `data.Count()` which raises an exception logged in administrator:
```
Starcounter.SqlException: Failed to process query: SELECT COUNT(T) FROM "UniformDocs"."Database"."TableRow" T ORDER BY T."FirstName" ASC: Incorrect order-by-clause w.r.t. group-by-clause. 
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String appName, String query, Boolean slowSql, Object[] values)
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String appName, String query, Boolean slowSQL, Object[] values)
   at Starcounter.QueryProcessor.Db.FullQueryProcess[T](String query, Boolean slowSQL, String appName, Object[] values)
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, String appName, Object[] values) in C:\	c_work\sc-18899\Level1\src\Starcounter\Mock\Db.cs:line 133
   at Starcounter.Db.SlowSQL(String query, Object[] values) in C:\	c_work\sc-18899\Level1\src\Starcounter\Mock\Db.cs:line 105
   at Starcounter.Linq.QueryExecutor`1.GetQueryResult(String sql, Object[] variables, QueryResultMethod queryResultMethod)
   at Starcounter.Linq.QueryExecutor`1.Execute[TResult](String sql, Object[] variables, QueryResultMethod queryResultMethod)
   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
   at Starcounter.Uniform.Queryables.QueryablePaginator`2.GetTotalRows(IQueryable`1 data) in C:\
epositories\Starcounter.Uniform\Starcounter.Uniform\Queryables\QueryablePaginator.cs:line 24
   at Starcounter.Uniform.Queryables.FilteredPaginatedDataProvider`2.ReloadRows() in C:\
epositories\Starcounter.Uniform\Starcounter.Uniform\Queryables\FilteredPaginatedDataProvider.cs:line 66
   at Starcounter.Uniform.Queryables.FilteredPaginatedDataProvider`2.get_CurrentPageRows() in C:\
epositories\Starcounter.Uniform\Starcounter.Uniform\Queryables\FilteredPaginatedDataProvider.cs:line 48
   at Starcounter.Uniform.ViewModels.UniDataTable.LoadRows() in C:\
epositories\Starcounter.Uniform\Starcounter.Uniform\ViewModels\UniDataTable.json.cs:line 44
   at Starcounter.Uniform.ViewModels.UniDataTable.ColumnsViewModel.Handle(Sort action) in C:\
epositories\Starcounter.Uniform\Starcounter.Uniform\ViewModels\UniDataTable.json.cs:line 147
   at Starcounter.Uniform.ViewModels.UniDataTable.ColumnsViewModel.JsonByExample.Schema.<>c.<.ctor>b__0_11(Json pup, Input`1 input)
   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value)
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.<>c__DisplayClass0_1.<Handle>b__0()
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\	c_work\sc-18899\Level1\src\Starcounter\TransactionManager.cs:line 557
   at Starcounter.Transaction.Scope(Action action) in C:\	c_work\sc-18899\Level1\src\Starcounter\Transaction.cs:line 233
   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value)
   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus)
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\	c_work\sc-18899\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 75
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\	c_work\sc-18899\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\	c_work\sc-18899\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 780
   at Starcounter.Session.Use(Action action)
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\	c_work\sc-18899\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 779
ScErrorCode=0
HResult=-2146233088
```

**Comment by un-tone** [comment]
Fixed. All the packages are updated.
