### ISSUE TITLE
Query with Enum.ToString() throws System.InvalidOperationException

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Starcounter.Linq#61]
Calling linq like this: 
`DbLinq.Objects<Host>().Where(x => x.Type.ToString().Contains("S").ToList();`
where `Host`:
```
    [Database]
    public class Host
    {
        public HostType Type { get; set; }
    }
```

and `HostType` is an `Enum` will result in exception:
```
System.InvalidOperationException: variable 'x' of type 'Inventory.Database.Host' referenced from scope '', but it is not defined
       at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
       at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
       at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
       at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
       at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
       at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
       at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
       at Starcounter.Linq.Helpers.ExpressionHelper.RetrieveMethodCallValue(MethodCallExpression node)
       at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
       at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
       at Starcounter.Linq.Visitors.RootVisitor`1.VisitWhere(Expression expression, QueryBuilder`1 state)
       at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
       at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
       at Starcounter.Linq.Queryable`1.GetEnumerator()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Starcounter.Uniform.Queryables.FilteredPaginatedDataProvider`2.get_CurrentPageRows()
       at Starcounter.Uniform.ViewModels.UniDataTable.LoadRows()
```

**Comment by PatrykSzwer** [comment]
Reason is that our SQL doesn't support `CONVERT` method and SC.Linq can't support ToString bc of that. Closing as not fixable.
