### ISSUE TITLE
Unable to cast object of type 'X' to type 'System.IConvertible'

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#78]
### Database Classes

```cs
[Database]
public class Item
{
    public string Name { get; set; }
}

[Database]
public class Group
{
    public string Name { get; set; }
}

[Database]
public class GroupItem
{
    public Group Group { get; set; }
    public Item Item { get; set; }
}
```

### LINQ Query

```cs
Group group = DbLinq.Objects<Group>().FirstOrDefault();

IQueryable<Item> query = DbLinq.Objects<GroupItem>()
    .Where(x => x.Group == group && x.Item != null)
    .Select(x => x.Item);

// This line triggers the exception.
bool any = query.Any();
```

### Exception

```
System.InvalidCastException: Unable to cast object of type 'Database.GroupItem' to type 'System.IConvertible'.
   at System.Convert.ToBoolean(Object value)
   at Starcounter.Linq.QueryExecutor`1.DeliftQueryResult(Object result, Type expectedType)
   at Starcounter.Linq.QueryExecutor`1.Execute[TResult](String sql, Object[] variables, QueryResultMethod queryResultMethod)
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
   at Playground.Program.<>c.<Main>b__1_1(String groupName)
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\tc_work\sc-20104\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 231
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\tc_work\sc-20104\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 89
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\tc_work\sc-20104\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 526
HResult=-2147467262

More information about this error may be available in the server error log.
```

### Environment

- `Starcounter-Custom-2.4.990.257 (Mar 28, 2019 5:26:15 PM)`.
- [`Starcounter.Linq 2.3.3`](https://www.nuget.org/packages/Starcounter.Linq/2.3.3).

**Comment by un-tone** [comment]
Fixed the issue. I'll close it after releasing a new version.

**Comment by un-tone** [comment]
Released in `*.4.0` versions.

**Comment by miyconst** [comment]
Thanks @un-tone for the fast fix.

**Comment by miyconst** [comment]
After the fix, the following query works:

```cs
IQueryable<Item> query = DbLinq.Objects<GroupItem>()
    .Where(x => x.Group == group && x.Item != null)
    .Select(x => x.Item);
```

But the following one throws exception:

```cs
IQueryable<ulong> query = DbLinq.Objects<GroupItem>()
    .Where(x => x.Group == group && x.Item != null)
    .Select(x => x.Item.GetObjectNo());
```

```
System.NotSupportedException: Specified method is not supported.
   at Starcounter.Linq.Visitors.StatelessVisitor`1.Visit(Expression node, T state)
   at Starcounter.Linq.Visitors.SelectVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
   at Playground.Program.<>c.<Main>b__1_1(String groupName)
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\tc_work\sc-20104\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 231
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\tc_work\sc-20104\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 89
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\tc_work\sc-20104\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 526
HResult=-2146233067

More information about this error may be available in the server error log.
```

**Comment by miyconst** [comment]
Closing in favor of - [LINQ: Implement support for IDatabaseContext.Get & IDatabaseContext.GetOid #1086](https://github.com/Starcounter/Starcounter.Nova/issues/1086).
