### ISSUE TITLE
Contains method throws InvalidOperationException when List<T> instead of T[] used

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#80]
Example:

```cs
List<int> ages = new List<int>() { 41, 42, 43 };
List<Person> persons = DbLinq.Objects<Person>().Where(p => ages.Contains(p.Age)).ToList();
```

```
System.InvalidOperationException: variable 'x' of type 'Database.Item' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at Starcounter.Linq.Helpers.ExpressionHelper.RetrieveMethodCallValue(MethodCallExpression node)
   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.RootVisitor`1.VisitWhere(Expression expression, QueryBuilder`1 state)
   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
   at Playground.Program.<>c.<Main>b__1_2()
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\tc_work\sc-20104\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 231
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\tc_work\sc-20104\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 89
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\tc_work\sc-20104\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 526
HResult=-2146233079

More information about this error may be available in the server error log.
```

**Comment by miyconst** [comment]
Closing as fixed, it is reproducible in `2.2.0`, but fixed in `2.4.1`.
